# Generated by Django 4.2.3 on 2023-07-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=225)),
                ('Last_Name', models.CharField(max_length=225)),
                ('middlename', models.CharField(max_length=255, null=True)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
