# Generated by Django 4.2.3 on 2023-08-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('details', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'courses',
            },
        ),
    ]
