# Generated by Django 4.2.3 on 2023-08-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(null=True, upload_to='course'),
        ),
    ]
