# Generated by Django 4.2.3 on 2023-08-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_course_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
