# Generated by Django 4.2.3 on 2023-08-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider')),
                ('title', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'sliders',
            },
        ),
    ]
